baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Knowledge Centre Open Data - TU Delft'

[pagination]
pagerSize = 10

[taxonomies]
year = "years"

[permalinks]
years = "/news/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
